# -*- coding: utf-8 -*-
"""image-classification-model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzZYuFILBRCnW-5XoS7vbWCtr8RsEg5r
"""

# ============================================
# CELL 1: Setup — Libraries
# ============================================
import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.applications import VGG16
from tensorflow.keras.callbacks import (
    EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
)

print(" TF Version:", tf.__version__)
print(" GPU:", tf.config.list_physical_devices('GPU'))

IMG_SIZE   = 150
BATCH_SIZE = 32

# ============================================
# CELL 2: Dataset — Direct Load From TensorFlow
# ============================================
print("Dataset is downloading.......")

(train_ds, val_ds, test_ds), info = tfds.load(
    'cats_vs_dogs',
    split=['train[:70%]', 'train[70%:85%]', 'train[85%:]'],
    with_info=True,
    as_supervised=True  # (image, label) format
)

print(f"\n Dataset ready!")
print(f"Train images : {len(train_ds)}")
print(f"Val images   : {len(val_ds)}")
print(f"Test images  : {len(test_ds)}")

# ============================================
# CELL 3: Preprocessing + Augmentation
# ============================================
def preprocess(image, label):
    image = tf.image.resize(image, [IMG_SIZE, IMG_SIZE])
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

def augment(image, label):
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_brightness(image, 0.2)
    image = tf.image.random_contrast(image, 0.8, 1.2)
    image = tf.image.random_saturation(image, 0.8, 1.2)
    return image, label

# Pipelines
train_data = (train_ds
    .map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    .map(augment,    num_parallel_calls=tf.data.AUTOTUNE)
    .shuffle(1000)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)
val_data = (val_ds
    .map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)
test_data = (test_ds
    .map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)
print("...Data pipelines is ready!")

# Sample images
plt.figure(figsize=(12, 4))
for i, (img, label) in enumerate(train_ds.take(6)):
    img_resized = tf.image.resize(img, [IMG_SIZE, IMG_SIZE]) / 255.0
    plt.subplot(2, 3, i+1)
    plt.imshow(img_resized.numpy())
    plt.title('Dog ' if label.numpy() == 1 else 'Cat ')
    plt.axis('off')
plt.suptitle('Sample Training Images', fontsize=13)
plt.tight_layout()
plt.show()

# ============================================
# CELL 4: VGG16 Transfer Learning Model
# ============================================
base_model = VGG16(
    weights='imagenet',
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)
base_model.trainable = False  # freeze

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=keras.optimizers.Adam(1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print(" Model is ready!")
model.summary()

# ============================================
# CELL 5: Phase 1 Training
# ============================================
os.makedirs('/content/models', exist_ok=True)

history1 = model.fit(
    train_data,
    epochs=15,
    validation_data=val_data,
    callbacks=[
        EarlyStopping(monitor='val_loss', patience=5,
                      restore_best_weights=True, verbose=1),
        ModelCheckpoint('/content/models/best_model.keras',
                        monitor='val_accuracy',
                        save_best_only=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.1,
                          patience=3, verbose=1)
    ]
)
print(f"\n Phase 1 Done!")
print(f"Best Val Accuracy: {max(history1.history['val_accuracy'])*100:.2f}%")

# ============================================
# CELL 6: Phase 2 — Fine Tuning
# ============================================

# Unfreeze the base model
base_model.trainable = True

# only the last 4 layers trainable
for layer in base_model.layers[:-4]:
    layer.trainable = False

print("Trainable layers:")
for layer in base_model.layers:
    print(f"  {layer.name}: {layer.trainable}")

# Very small learning rate — save pretrained weights
model.compile(
    optimizer=keras.optimizers.Adam(1e-5),  # 10x chota!
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print("\n Start Fine Tuning!")
history2 = model.fit(
    train_data,
    epochs=10,
    validation_data=val_data,
    callbacks=[
        EarlyStopping(
            monitor='val_loss',
            patience=3,
            restore_best_weights=True,
            verbose=1
        ),
        ModelCheckpoint(
            '/content/models/final_model.keras',
            monitor='val_accuracy',
            save_best_only=True,
            verbose=1
        )
    ]
)

print(f"\n Fine Tuning Done!")
print(f"Phase 1 Best: 90.83%")
print(f"Phase 2 Best: {max(history2.history['val_accuracy'])*100:.2f}%")

# ============================================
# CELL 7: Final Results — Graphs + Test Eval
# ============================================
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# Training curves — combine both phases
all_acc  = history1.history['accuracy']  + history2.history['accuracy']
all_val  = history1.history['val_accuracy'] + history2.history['val_accuracy']
all_loss = history1.history['loss']      + history2.history['loss']
all_vloss= history1.history['val_loss']  + history2.history['val_loss']
phase1_end = len(history1.history['accuracy'])

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Accuracy graph
ax1.plot(all_acc,  label='Train',      color='#4f46e5', linewidth=2)
ax1.plot(all_val,  label='Validation', color='#f97316', linewidth=2)
ax1.axvline(x=phase1_end-1, color='gray',
            linestyle='--', linewidth=1.5, label='Fine-tuning start')
ax1.fill_between(range(phase1_end),
                 all_val[:phase1_end], alpha=0.1, color='#4f46e5')
ax1.fill_between(range(phase1_end, len(all_val)),
                 all_val[phase1_end:], alpha=0.1, color='#f97316')
ax1.set_title('Model Accuracy — Phase 1 + Fine Tuning', fontsize=13)
ax1.set_xlabel('Epoch'); ax1.set_ylabel('Accuracy')
ax1.legend(); ax1.grid(alpha=0.3)
ax1.set_ylim([0.8, 1.0])

# Loss graph
ax2.plot(all_loss,  label='Train',      color='#4f46e5', linewidth=2)
ax2.plot(all_vloss, label='Validation', color='#ef4444', linewidth=2)
ax2.axvline(x=phase1_end-1, color='gray',
            linestyle='--', linewidth=1.5, label='Fine-tuning start')
ax2.set_title('Model Loss — Phase 1 + Fine Tuning', fontsize=13)
ax2.set_xlabel('Epoch'); ax2.set_ylabel('Loss')
ax2.legend(); ax2.grid(alpha=0.3)

plt.suptitle('VGG16 Transfer Learning — Cats vs Dogs', fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig('/content/training_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print("Graph saved!")

# ── Test Set Final Evaluation ──
print("\n" + "="*50)
print("FINAL TEST SET EVALUATION")
print("="*50)

test_loss, test_acc = model.evaluate(test_data, verbose=0)
print(f"Test Accuracy : {test_acc*100:.2f}%")
print(f"Test Loss     : {test_loss:.4f}")

# ── Confusion Matrix ──
y_pred_prob = model.predict(test_data, verbose=0)
y_pred = (y_pred_prob > 0.5).astype(int).flatten()
y_true = np.concatenate([y for _, y in test_data], axis=0)
y_true = y_true[:len(y_pred)]

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Cat','Dog'],
            yticklabels=['Cat','Dog'],
            annot_kws={'size': 14})
plt.title(f'Confusion Matrix — Test Accuracy: {test_acc*100:.2f}%',
          fontsize=12)
plt.ylabel('Actual Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.savefig('/content/confusion_matrix.png', dpi=150)
plt.show()

# ── Classification Report ──
print("\nDetailed Report:")
print(classification_report(y_true, y_pred,
      target_names=['Cat', 'Dog']))

# ============================================
# CELL 8:Upload your image and predict
# ============================================
from google.colab import files
from tensorflow.keras.preprocessing import image as keras_image
from PIL import Image as PILImage
import numpy as np

print("Upload your cat or dog image!")
uploaded = files.upload()

for filename in uploaded.keys():
    # Load + preprocess
    img = keras_image.load_img(filename, target_size=(150, 150))
    img_array = keras_image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0) / 255.0

    # Predict
    pred = model.predict(img_array, verbose=0)[0][0]
    label = "Dog" if pred > 0.5 else "Cat"
    conf  = round(pred*100, 1) if pred > 0.5 else round((1-pred)*100, 1)

    # Display
    plt.figure(figsize=(5, 5))
    plt.imshow(PILImage.open(filename))
    plt.title(f'Prediction: {label}\nConfidence: {conf}%',
              fontsize=14, fontweight='bold',
              color='green' if conf > 85 else 'orange')
    plt.axis('off')
    plt.tight_layout()
    plt.show()

    print(f"\nResult: {label} — {conf}% confident!")
    print(f"Raw score: {pred:.4f} (>0.5=Dog, <0.5=Cat)")

# Download Model
print("\nModel is downloading...")
files.download('/content/models/final_model.keras')
files.download('/content/training_curves.png')
files.download('/content/confusion_matrix.png')

# ============================================
# Download Model
# ============================================
from google.colab import files

# Model download
files.download('/content/models/final_model.keras')

print("Model download!")